import base64
import json
import os
import re
import time
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import quote
from urllib.parse import urlparse

import requests
from dotenv import load_dotenv


GITHUB_API_BASE_URL = "https://api.github.com"
RAW_DATA_DIR = Path("data/raw")
INDEXING_MODES = {
    "recent": {
        "issues": "recent",
        "pulls": "recent",
        "commits": "recent",
        "docs": False,
    },
    "standard": {
        "issues": "all",
        "pulls": "all",
        "commits": "selected",
        "docs": True,
    },
    "deep": {
        "issues": "all",
        "pulls": "all",
        "commits": "all",
        "docs": True,
    },
}
STANDARD_COMMIT_SCAN_PAGES = 3
STANDARD_SELECTED_COMMIT_LIMIT = 100
RECENT_ISSUE_MAX_PAGES = 5
STANDARD_DOC_LIMIT = 300
GITHUB_GET_TIMEOUT_SECONDS = 30
GITHUB_GET_TIMEOUT_RETRIES = 2
LOW_SIGNAL_COMMIT_PATTERNS = (
    "typo",
    "format",
    "lint",
    "bump",
    "update dependency",
    "dependabot",
)
LOW_VALUE_DOC_PATH_PATTERNS = (
    "changelog",
    "changes/",
    "newsfragments/",
    "release-notes/",
    "generated",
    "_generated",
    "autogenerated",
    "_build/",
    "site/",
)
SPINNER_FRAMES = ("|", "/", "-", "\\")


@dataclass
class IngestResult:
    output_dir: Path
    mode: str
    fetched_counts: dict[str, int]
    warnings: list[str]


def parse_github_url(repo_url) -> tuple[str, str]:
    parsed_url = urlparse(repo_url)
    path_parts = [part for part in parsed_url.path.split("/") if part]

    if parsed_url.scheme not in {"http", "https"}:
        raise ValueError("GitHub URL must start with http:// or https://")

    if parsed_url.netloc.lower() != "github.com" or len(path_parts) < 2:
        raise ValueError("Expected a GitHub URL like https://github.com/owner/repo")

    return path_parts[0], path_parts[1].removesuffix(".git")


def _github_get(path: str, params=None):
    load_dotenv()

    headers = {"Accept": "application/vnd.github+json"}
    token = os.environ.get("GITHUB_TOKEN")

    if token:
        headers["Authorization"] = f"Bearer {token}"

    url = f"{GITHUB_API_BASE_URL}{path}"
    for attempt in range(GITHUB_GET_TIMEOUT_RETRIES + 1):
        try:
            response = requests.get(
                url,
                headers=headers,
                params=params,
                timeout=GITHUB_GET_TIMEOUT_SECONDS,
            )
            break
        except requests.exceptions.Timeout:
            if attempt >= GITHUB_GET_TIMEOUT_RETRIES:
                raise
            time.sleep(attempt + 1)

    try:
        response.raise_for_status()
    except requests.HTTPError as error:
        status_code = response.status_code
        message = response.text.strip() or response.reason
        raise RuntimeError(
            f"GitHub API request failed ({status_code}): {message}"
        ) from error

    return response.json()


def _github_token_missing() -> bool:
    load_dotenv()
    return not os.environ.get("GITHUB_TOKEN")


def github_token_missing() -> bool:
    return _github_token_missing()


def _indexing_warnings(mode: str) -> list[str]:
    warnings = []
    if _github_token_missing():
        warnings.append(
            "GitHub token not found. GitHub API rate limits may be lower."
        )
    if mode == "deep":
        warnings.append(
            "Deep mode may take a long time and may hit GitHub rate limits."
        )
    if mode == "standard":
        warnings.append(
            "Some commit history may not be indexed in standard mode."
        )
    return warnings


def _fetch_paginated(
    path: str,
    params=None,
    per_page: int = 100,
    max_pages: int | None = None,
    progress_label: str | None = None,
):
    records = []
    page = 1
    spinner_index = 0

    while True:
        page_params = dict(params or {})
        page_params["per_page"] = per_page
        page_params["page"] = page
        batch = _github_get(path, params=page_params)

        if not batch:
            break

        records.extend(batch)
        if progress_label:
            spinner_index = _print_spinner_progress(
                progress_label,
                f"page {page}, total: {len(records)}",
                spinner_index,
            )

        if len(batch) < per_page:
            break

        if max_pages is not None and page >= max_pages:
            break

        page += 1

    if progress_label:
        _finish_spinner_progress(
            progress_label,
            f"fetched {len(records)} total",
        )

    return records


def fetch_issues(owner: str, repo: str, limit=100):
    records = _fetch_paginated(
        f"/repos/{owner}/{repo}/issues",
        params=_issue_query_params(),
        per_page=limit,
        max_pages=RECENT_ISSUE_MAX_PAGES,
        progress_label="issues",
    )
    return _filter_issue_records(records)


def fetch_pull_requests(owner: str, repo: str, limit=100):
    return _fetch_paginated(
        f"/repos/{owner}/{repo}/pulls",
        params={"state": "all"},
        per_page=limit,
        max_pages=1,
        progress_label="pull requests",
    )


def fetch_commits(owner: str, repo: str, limit=100):
    return _fetch_paginated(
        f"/repos/{owner}/{repo}/commits",
        per_page=limit,
        max_pages=1,
        progress_label="commits",
    )


def fetch_all_issues(owner: str, repo: str):
    records = _fetch_paginated(
        f"/repos/{owner}/{repo}/issues",
        params=_issue_query_params(),
        progress_label="issues",
    )
    return _filter_issue_records(records)


def _issue_query_params() -> dict:
    return {
        "state": "all",
        "sort": "updated",
        "direction": "desc",
    }


def _filter_issue_records(records: list[dict]) -> list[dict]:
    issues = [record for record in records if "pull_request" not in record]
    skipped_pull_requests = len(records) - len(issues)

    print("Issue endpoint summary:")
    print(f"- Raw issue endpoint items fetched: {len(records)}")
    print(f"- Actual issues after filtering PRs: {len(issues)}")
    print(f"- Pull requests skipped from issues endpoint: {skipped_pull_requests}")

    return issues


def fetch_all_pull_requests(owner: str, repo: str):
    return _fetch_paginated(
        f"/repos/{owner}/{repo}/pulls",
        params={"state": "all"},
        progress_label="pull requests",
    )


def fetch_all_commits(owner: str, repo: str):
    return _fetch_paginated(
        f"/repos/{owner}/{repo}/commits",
        progress_label="commits",
    )


def fetch_selected_commits(owner: str, repo: str):
    commits = _fetch_paginated(
        f"/repos/{owner}/{repo}/commits",
        max_pages=STANDARD_COMMIT_SCAN_PAGES,
        progress_label="commits",
    )
    selected_commits = _select_useful_commits(commits)
    print(f"  selected useful commits: {len(selected_commits)}")
    return selected_commits


def fetch_docs(owner: str, repo: str, mode: str = "standard"):
    repository = _github_get(f"/repos/{owner}/{repo}")
    default_branch = repository["default_branch"]
    tree = _github_get(
        f"/repos/{owner}/{repo}/git/trees/{quote(default_branch, safe='')}",
        params={"recursive": "1"},
    )

    doc_items = _select_documentation_items(tree.get("tree", []), mode)
    print(f"  documentation files selected: {len(doc_items)}")

    docs = []
    skipped_count = 0
    spinner_index = 0
    for index, item in enumerate(doc_items, start=1):
        path = item.get("path") or ""
        encoded_path = quote(path, safe="/")
        try:
            content_record = _github_get(
                f"/repos/{owner}/{repo}/contents/{encoded_path}"
            )
        except requests.exceptions.Timeout:
            skipped_count += 1
            _clear_spinner_progress()
            print(f"Skipped doc due to timeout: {path}")
            spinner_index = _print_spinner_progress(
                "docs",
                f"fetched {len(docs)}/{len(doc_items)}, skipped {skipped_count}",
                spinner_index,
            )
            continue

        content = _decode_content(content_record)
        docs.append(
            {
                "path": path,
                "url": content_record.get("html_url") or item.get("url"),
                "content": content,
                "text": content,
            }
        )
        spinner_index = _print_spinner_progress(
            "docs",
            f"fetched {len(docs)}/{len(doc_items)}, skipped {skipped_count}",
            spinner_index,
        )

    _finish_spinner_progress(
        "docs",
        f"fetched {len(docs)}/{len(doc_items)}, skipped {skipped_count}",
    )

    return docs


def _select_documentation_items(tree_items: list[dict], mode: str) -> list[dict]:
    doc_items = [
        item
        for item in tree_items
        if item.get("type") == "blob"
        and _is_documentation_path(item.get("path") or "")
        and not _is_low_value_doc_path(item.get("path") or "")
    ]
    docs_en_exists = any(
        (item.get("path") or "").lower().startswith("docs/en/")
        for item in doc_items
    )

    if mode == "standard":
        selected_items = _select_standard_docs(doc_items, docs_en_exists)
        return selected_items[:STANDARD_DOC_LIMIT]

    if docs_en_exists:
        return [
            item
            for item in doc_items
            if not _is_translation_doc_path(item.get("path") or "")
        ]

    return doc_items


def _select_standard_docs(doc_items: list[dict], docs_en_exists: bool) -> list[dict]:
    selected_items = []
    for item in doc_items:
        path = item.get("path") or ""
        lower_path = path.lower()

        if _is_top_level_markdown_path(lower_path):
            selected_items.append(item)
        elif docs_en_exists and lower_path.startswith("docs/en/"):
            selected_items.append(item)
        elif not docs_en_exists and lower_path.startswith("docs/"):
            selected_items.append(item)

    return selected_items


def _is_documentation_path(path: str) -> bool:
    lower_path = path.lower()

    if "/" not in path and lower_path.endswith(".md"):
        return True

    return lower_path.startswith("docs/") and lower_path.endswith((".md", ".mdx"))


def _is_top_level_markdown_path(lower_path: str) -> bool:
    return "/" not in lower_path and lower_path.endswith(".md")


def _is_low_value_doc_path(path: str) -> bool:
    lower_path = path.lower()
    return any(pattern in lower_path for pattern in LOW_VALUE_DOC_PATH_PATTERNS)


def _is_translation_doc_path(path: str) -> bool:
    lower_path = path.lower()
    if not lower_path.startswith("docs/"):
        return False

    path_parts = lower_path.split("/")
    return len(path_parts) > 2 and path_parts[1] != "en"


def _decode_content(content_record: dict) -> str:
    if content_record.get("encoding") != "base64":
        return content_record.get("content") or ""

    encoded_content = (content_record.get("content") or "").replace("\n", "")
    return base64.b64decode(encoded_content).decode("utf-8", errors="replace")


def _print_spinner_progress(label: str, message: str, spinner_index: int) -> int:
    frame = SPINNER_FRAMES[spinner_index % len(SPINNER_FRAMES)]
    print(f"\r  {frame} {label}: {message}", end="", flush=True)
    return spinner_index + 1


def _finish_spinner_progress(label: str, message: str):
    print(f"\r  {label}: {message}")


def _clear_spinner_progress():
    print("\r", end="", flush=True)


def _select_useful_commits(commits: list[dict]) -> list[dict]:
    selected = []
    fallback = []

    for commit in commits:
        message = commit.get("commit", {}).get("message") or ""
        if _is_low_signal_commit(message):
            continue

        if _is_useful_commit_message(message):
            selected.append(commit)
        else:
            fallback.append(commit)

        if len(selected) >= STANDARD_SELECTED_COMMIT_LIMIT:
            return selected[:STANDARD_SELECTED_COMMIT_LIMIT]

    remaining_slots = STANDARD_SELECTED_COMMIT_LIMIT - len(selected)
    return selected + fallback[:remaining_slots]


def _is_useful_commit_message(message: str) -> bool:
    first_line = message.splitlines()[0] if message else ""
    return (
        "#" in message and re.search(r"#\d+", message) is not None
    ) or first_line.startswith("Merge ") or len(message.strip()) >= 120


def _is_low_signal_commit(message: str) -> bool:
    normalized_message = message.lower()
    return any(
        pattern in normalized_message for pattern in LOW_SIGNAL_COMMIT_PATTERNS
    )


def _save_json(path: Path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")


def ingest_repo(
    repo_url: str,
    mode: str = "standard",
    raw_data_dir: Path | None = None,
) -> IngestResult:
    owner, repo = parse_github_url(repo_url)
    if mode not in INDEXING_MODES:
        raise ValueError(f"Unknown indexing mode: {mode}")

    mode_config = INDEXING_MODES[mode]
    raw_data_dir = raw_data_dir or RAW_DATA_DIR
    output_dir = raw_data_dir / f"{owner}_{repo}"
    warnings = _indexing_warnings(mode)

    print(f"Fetching GitHub artifacts for {owner}/{repo} using mode: {mode}")

    print("Fetching issues...")
    issues = (
        fetch_all_issues(owner, repo)
        if mode_config["issues"] == "all"
        else fetch_issues(owner, repo)
    )

    print("Fetching pull requests...")
    pull_requests = (
        fetch_all_pull_requests(owner, repo)
        if mode_config["pulls"] == "all"
        else fetch_pull_requests(owner, repo)
    )

    print("Fetching commits...")
    if mode_config["commits"] == "all":
        commits = fetch_all_commits(owner, repo)
    elif mode_config["commits"] == "selected":
        commits = fetch_selected_commits(owner, repo)
    else:
        commits = fetch_commits(owner, repo)

    docs = []
    if mode_config["docs"]:
        print("Fetching markdown documentation...")
        docs = fetch_docs(owner, repo, mode=mode)
    else:
        print("Skipping documentation for recent mode.")

    _save_json(output_dir / "issues.json", issues)
    _save_json(output_dir / "pulls.json", pull_requests)
    _save_json(output_dir / "commits.json", commits)
    _save_json(output_dir / "docs.json", docs)

    return IngestResult(
        output_dir=output_dir,
        mode=mode,
        fetched_counts={
            "issues": len(issues),
            "pull_requests": len(pull_requests),
            "commits": len(commits),
            "docs": len(docs),
        },
        warnings=warnings,
    )
